package com.jonak.entity;
// Generated Jun 9, 2017 8:23:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name="address"
    ,catalog="home_master"
)
public class Address  implements java.io.Serializable {


     private Integer id;
     private String street;
     private String house;
     private Set<Contact> contacts = new HashSet<Contact>(0);

    public Address() {       
    }

	
    public Address(String street, String house) {
        this.street = street;
        this.house = house;
    }
    public Address(String street, String house, Set<Contact> contacts) {
       this.street = street;
       this.house = house;
       this.contacts = contacts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="street", nullable=false, length=20)
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="house", nullable=false, length=20)
    public String getHouse() {
        return this.house;
    }
    
    public void setHouse(String house) {
        this.house = house;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="address")
    public Set<Contact> getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Set<Contact> contacts) {
        this.contacts = contacts;
    }




}


