package com.jonak.entity;
// Generated May 27, 2017 10:23:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name="contact"
    ,catalog="home_master"
)
public class Contact  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String mobile;
     private String address;
     private Date birthday;
     private boolean isFnf;
     private String email;
     private String typeOfContact;
     private String description;

    public Contact() {
    }

    public Contact(String name, String mobile, String address, Date birthday, boolean isFnf, String email, String typeOfContact, String description) {
       this.name = name;
       this.mobile = mobile;
       this.address = address;
       this.birthday = birthday;
       this.isFnf = isFnf;
       this.email = email;
       this.typeOfContact = typeOfContact;
       this.description = description;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="mobile", nullable=false, length=15)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="address", nullable=false, length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthday", nullable=false, length=10)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    
    @Column(name="is_fnf", nullable=false)
    public boolean isIsFnf() {
        return this.isFnf;
    }
    
    public void setIsFnf(boolean isFnf) {
        this.isFnf = isFnf;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="type_of_contact", nullable=false, length=20)
    public String getTypeOfContact() {
        return this.typeOfContact;
    }
    
    public void setTypeOfContact(String typeOfContact) {
        this.typeOfContact = typeOfContact;
    }

    
    @Column(name="description", nullable=false, length=200)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


