package com.jonak.entity;
// Generated Jun 9, 2017 8:23:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name="task"
    ,catalog="home_master"
)
public class Task  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String taskDescription;
     private Date dateOfCreation;
     private Date scheduleDate;
     private String status;

    public Task() {
    }

    public Task(String name, String taskDescription, Date dateOfCreation, Date scheduleDate, String status) {
       this.name = name;
       this.taskDescription = taskDescription;
       this.dateOfCreation = dateOfCreation;
       this.scheduleDate = scheduleDate;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="task_description", nullable=false, length=200)
    public String getTaskDescription() {
        return this.taskDescription;
    }
    
    public void setTaskDescription(String taskDescription) {
        this.taskDescription = taskDescription;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_of_creation", nullable=false, length=10)
    public Date getDateOfCreation() {
        return this.dateOfCreation;
    }
    
    public void setDateOfCreation(Date dateOfCreation) {
        this.dateOfCreation = dateOfCreation;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="schedule_date", nullable=false, length=10)
    public Date getScheduleDate() {
        return this.scheduleDate;
    }
    
    public void setScheduleDate(Date scheduleDate) {
        this.scheduleDate = scheduleDate;
    }

    
    @Column(name="status", nullable=false, length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


