package com.jonak.entity;
// Generated May 27, 2017 10:23:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TypeOfContact generated by hbm2java
 */
@Entity
@Table(name="type_of_contact"
    ,catalog="home_master"
)
public class TypeOfContact  implements java.io.Serializable {


     private Integer id;
     private String type;
     private String description;

    public TypeOfContact() {
    }

    public TypeOfContact(String type, String description) {
       this.type = type;
       this.description = description;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="type", nullable=false, length=10)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="description", nullable=false, length=200)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


